-- V1__create_notes_table.sql
-- Create the notes table with owner, title, body, and timestamp columns.
CREATE TABLE notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Index to sort by newest first efficiently when querying by owner.
CREATE INDEX idx_notes_owner_created_at_desc ON notes (owner, created_at DESC);
